# Generated by Django 4.1.4 on 2023-01-28 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restfoodmodel',
            old_name='food_prize',
            new_name='food_price',
        ),
    ]
