# Generated by Django 4.1.4 on 2023-01-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
    ]
