# Generated by Django 4.1.4 on 2023-01-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_remove_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='amount_paid',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='status',
            field=models.CharField(default='not_paid', max_length=100),
        ),
    ]
