# Generated by Django 4.1.4 on 2023-01-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0005_alter_paymentmodel_amount_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
    ]
