# Generated by Django 4.1.4 on 2023-01-28 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0006_remove_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='payment',
        ),
    ]
